const products = [
  {
    id: 1,
    name: 'T-shirt Python',
    description: 'Uma camiseta confortável e estilosa com o logotipo do Python.',
    price: 20,
    category: 'Acessórios',
    status: 'Em estoque',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/640px-Python.svg.png',
  },
  {
    id: 2,
    name: 'Caneca Python',
    description: 'Uma caneca de cerâmica com o logotipo do Python.',
    price: 20,
    category: 'Acessórios',
    status: 'Em estoque',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/640px-Python.svg.png',
  },
  {
    id: 3,
    name: 'Casaco Python',
    description: 'Um casaco confortável e estiloso com o logotipo do Python.',
    price: 50,
    category: 'Vestuário',
    status: 'Em estoque',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/640px-Python.svg.png',
  },
  {
    id: 4,
    name: 'Programa Python',
    description: 'Um livro com instruções sobre programação em Python.',
    price: 30,
    category: 'Livros',
    status: 'Em estoque',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/640px-Python.svg.png',
  },
  {
    id: 5,
    name: 'Mouse Python',
    description: 'Um mouse de computador tematizado com o logo do Python.',
    price: 15,
    category: 'Acessórios',
    status: 'Em estoque',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/640px-Python.svg.png',
  },
  {
    id: 6,
    name: 'Boné Python',
    description: 'Um boné estiloso com o logotipo do Python.',
    price: 10,
    category: 'Acessórios',
    status: 'Em estoque',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/640px-Python.svg.png',
  },
  {
    id: 7,
    name: 'Chaveiro Python',
    description: 'Um chaveiro com o emblema do Python.',
    price: 5,
    category: 'Acessórios',
    status: 'Em estoque',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/640px-Python.svg.png',
  },
  {
    id: 8,
    name: 'Mochila Python',
    description: 'Uma mochila espaçosa com o logotipo do Python.',
    price: 40,
    category: 'Acessórios',
    status: 'Em estoque',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/640px-Python.svg.png',
  },
  {
    id: 9,
    name: 'Mousepad Python',
    description: 'Um mousepad grande com design do Python.',
    price: 8,
    category: 'Acessórios',
    status: 'Em estoque',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/640px-Python.svg.png',
  },
  {
    id: 10,
    name: 'Camiseta Python 2.0',
    description: 'Uma versão atualizada da camiseta Python.',
    price: 25,
    category: 'Vestuário',
    status: 'Em estoque',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/640px-Python.svg.png',
  },
];


module.exports = {
	products,
}